apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: cluster4
  namespace: observability
spec:
  releaseName: cluster4
  targetNamespace: observability
  chart:
    spec:
      chart: /charts/elastic-cluster
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:
    myvar: yeah
        
        
