apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
spec:
  version: {{ .Values.elastic.version }}
  nodeSets:
  - name: {{ .Values.myvar}}
    count: 1
    config:
      node.store.allow_mmap: false