apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}  
spec:
  version: {{ .Values.elastic.version }}
  nodeSets:
  - name: master
    count: {{ .Values.master.nodeset.count}}
    config:
      node.roles: ['master']
      node.store.allow_mmap: false

  - name: data
    count: {{ .Values.data.nodeset.count}}
    config:
      node.roles: ['data']
      node.store.allow_mmap: false      

{{ if gt ( .Values.datahot.nodeset.count |toString|atoi) 0 }}
  - name: datahot
    count: {{ .Values.datahot.nodeset.count}}
    config:
      node.roles: ['data_hot']
      node.store.allow_mmap: false            
{{ end }}      