apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: {{ .Release.Name}}-es-ingress
  namespace: {{ .Release.Namespace}}
spec:
  rules:
  - host: {{ .Release.Name}}-es
    http:
      paths: 
      - host: elasticsearch
        path: /
        backend:
          service:
            name: {{ .Release.Name}}-es-http
            port:
              number: 9200
        pathType: ImplementationSpecific

