{{ if  .Values.ilms.mypolicy }}
apiVersion: elastic.elastic-operator/v1
kind: ILM
metadata:
  name: {{ .Release.Name}}-ilm-mypolicy
  namespace: observability
spec:
  name: mypolicy
  cluster: {{ .Release.Name}}
  body: |
          {
            "policy": {
              "_meta": {
                "description": "used for nginx log",
                "project": {
                  "name": "myProject",
                  "department": "myDepartment"
                }
              },
              "phases": {
                "warm": {
                  "min_age": "10d",
                  "actions": {
                    "forcemerge": {
                      "max_num_segments": 1
                    }
                  }
                },
                "delete": {
                  "min_age": "30d",
                  "actions": {
                    "delete": {}
                  }
                }
              }
            }
          }
{{ end}}            