{{ if  .Values.indextemplates.api }}
apiVersion: elastic.elastic-operator/v1
kind: IndexTemplate
metadata:
  name: {{ .Release.Name}}-indextemplate-api
  namespace: {{ .Release.Namespace}}
spec:
  name: api
  cluster: {{ .Release.Name}}
  body: |
        {
          "index_patterns": ["api-*"],
          "template": {
            "settings": {
              "number_of_shards": 1
            },
            "mappings": {
              "_source": {
                "enabled": true
              },
              "properties": {
                "host_name": {
                  "type": "keyword"
                },
                "created_at": {
                  "type": "date",
                  "format": "EEE MMM dd HH:mm:ss Z yyyy"
                }
              }
            },
            "aliases": {
              "mydata": { }
            }
          },
          "priority": 500,
          "composed_of": ["mycomponent1", "ecs" , "ecshost", "ecs3"], 
          "version": 3,
          "_meta": {
            "description": "my custom bla bla"
          }
        }  
{{ end}}            