apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: {{ .Release.Name}}-kb-ingress
  namespace: {{ .Release.Namespace}}
spec:
  rules:
  - host: {{ .Release.Name}}.k8s
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name}}-kb-http
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific

