apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.elastic.version}}
  count: 1
  elasticsearchRef:
    name: {{ .Release.Name }}
  podTemplate:
    spec:  
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        runAsUser: 1000
  config:
    monitoring:
      ui:
        ccs:
          enabled: false
        
            