apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.elastic.version}}
  count: 1
  elasticsearchRef:
    name: {{ .Release.Name }}
  config:
    monitoring:
      ui:
        ccs:
          enabled: false
            