{{ if   .Values.watchers.watcher1 }}
apiVersion: elastic.elastic-operator/v1
kind: Watcher
metadata:
  name: {{ .Release.Name}}-watcher-watcher1
  namespace: {{ .Release.Namespace}}
spec:
  name: watcher1
  cluster: {{ .Release.Name}}
  body: |
          {
            "trigger" : {
              "schedule" : { "cron" : "0 0/1 * * * ?" }
            },
            "input" : {
              "search" : {
                "request" : {
                  "indices" : [
                    "logstash*"
                  ],
                  "body" : {
                    "query" : {
                      "bool" : {
                        "must" : {
                          "match": {
                            "response": 404
                          }
                        },
                        "filter" : {
                          "range": {
                            "@timestamp": {
{{`

                              "from": "{{ctx.trigger.scheduled_time}}||-5m",
                              "to": "{{ctx.trigger.triggered_time}}"
`}}                              
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "condition" : {
              "compare" : { "ctx.payload.hits.total" : { "gt" : 0 }}
            },
            "actions" : {
              "email_admin" : {
                "email" : {
                  "to" : "admin@domain.host.com",
                  "subject" : "404 recently encountered"
                }
              }
            }
          }  
{{ end }}