apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: cluster14
  namespace: observability
spec:
  releaseName: cluster14
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/elastic-cluster
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:

    cluster:

      elastic:
        version: 8.2.0

      master:
        nodeset: 
          count: 1    

      data:
        nodeset: 
          count: 0

      datahot:
        nodeset: 
          count: 1
          
      ingest:
        nodeset: 
          count: 1

    scripts:
      script1: true  

    watchers:
      watcher1: true
      watcher2: true
      sprint: true

    transforms:
      transform1: true

    dataviews:
      hello: true
      kibana: false

    connectors:
      hello: true

    ingestpipelines:
      mypipeline: true
      api: true
      test3: True
      test4: True
      helloworld: True
      sprint: True

    ilms:
      mypolicy: true

    slms:
      mypolicy: true

    repos:
      myrepo: true

    componenttemplates:
      mycomponent1: true
      ecs: true
      ecshost: true
      ecs2: true
      ecs3: true

    indextemplates:
      api: true
      metricbeat: true
      metricbeat1: true
      metricbeat2: true
      metricbeat3: true
      metricbeat4: true
      metricbeat5: true
      metricbeat6: true
      metricbeat7: true
      metricbeat8: true
      metricbeat9: true

    rolemappings:
      mapping1: true
      oidc1: true

    legacyindextemplates:
      myindextemplate: true
      winlogbeat: false
      api: false
      role6: true


    clustersettings:
      recovery: false
      monitoring: true
      routingallocationdisk: false

    roles: 
      role3: true
      role4: true
      role5: false
      role6: true
      role7: true
      role8: true

    apikeys:
      metricbeat: true
      filebeat: true
      dummy: true
      onehour: true
      noexpire: true
      threehour: true
      sprint: true

    kibanaspaces:
      metricbeat: false
      winlogbeat: true
      rally: true
      dummy: true
      api: true
      filebeat: true
      helloworld: true
      sprint: true

