myvar: prod

oidc:
  enabled: true
  claimurl: "http://example.com/claims/groups"


production:
  enabled: false


elastic:
  version: 8.1.0

master:
  nodeset:
    name: master 
    count: 3
    roles: 
      - '"master"'
      - '"remote_cluster_client"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

data:
  nodeset: 
    name: data
    count: 2    
    roles: 
      - '"data"'
      - '"ml"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datahot:
  nodeset: 
    name: datahot
    count: 0        
    roles: 
      - '"data_hot"'
      - '"data_content"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

ingest:
  nodeset: 
    name: ingest
    count: 0            
    roles: 
      - '"ingest"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

rolemappings:
  donotremoveme: false

ingestpipelines:
  donotremoveme: false

ilms:
  mypolicy: False

slms:
  mypolicy: False

repos:
  myrepo: False

apikeys:
  donotremoveme: false

roles:
  donotremoveme: false

kibanaspaces:
  donotremoveme: false

clustersettings:
  donotremoveme: false

legacyindextemplates:
  donotremoveme: false

indextemplates:
  donotremoveme: false

componenttemplates:
  donotremoveme: false

scripts:
  donotremoveme: false

watchers:
  donotremoveme: false

transforms:
  donotremoveme: false

dataviews:
  donotremoveme: false

connectors:
  donotremoveme: false
