configmap:
  apikeyRollover: "75"
  maxRetries: "30"
  keyVault: "https://flux-akv.azurewebsites.net/api/FluxDemo"
  elasticUserSecretSuffix: "-es-elastic-user"
  ReconLoopInterval: "300"
  ApiGroup: "elastic.elastic-operator"
  ApiVersion: "v1"
  CacheTtl: "15"
  Namespace: "{{ .Release.Namespace}}"
  healthPort: "15001"
