ConfigMap:
  apikeyRollover: "75"
  maxRetries: "30"
  keyVault: "https://flux-akv.azurewebsites.net/api/FluxDemo"
  elasticUserSecretSuffix: "-es-elastic-user"
  ReconLoopInterval: "300"
  ApiGroup: "elastic.elastic-operator"
  ApiVersion: "v1"
  CacheTtl: "15"
  Namespace: "observability"
  healthPort: "15001"
  LongRunningCheck: "1"
  LongRunningMax: "5"

Operator:
  Sa: "sa"
  Role: "role"

limits:
  memory: 4Gi
  cpu: 2
requests:
  memory: 2Gi
  cpu: 1
