---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-logs
  namespace: observability
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./charts/elastic-logs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-elastic
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env
  patches:
    - patch: |-
        - op: replacexx
          path: /spec/values/topology/enabled
          value: true

      target:
        kind: HelmRelease
        name: elastic-logs
        namespace: observability