---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-logs
  namespace: observability
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./charts/elastic-logs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-elastic
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: elastic-logs
          namespace: observability
        spec:
          releaseName: elastic-logs
          targetNamespace: observability        
          values:

            filebeat:
              config: 
                version: 8.3.1

                collect: elasticlogs
                output:
                  cluster: cluster14
      target:
        kind: HelmRelease
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: elastic-logs
      namespace: observability