apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: elastic-logs
  namespace: observability
spec:
  releaseName: elastic-logs
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/elastic-logs
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:

    elastic:
      config: 
        version: 8.3.1
        monitoring:
          enabled: true
          cluster: cluster14
          period: 10s