{{ if   .Values.monitoring }}
apiVersion: elastic.elastic-operator/v1
kind: ElasticUser
metadata:
  name: {{ .Release.Name}}-users-monitoring
  namespace: {{ .Release.Namespace}}
spec:
  name: monitoring
  cluster: {{ .Release.Name}}
  secret: {{ .Release.Name}}-users-monitoring
  k8skey: password
  k8stype: Opaque
  body: |
      {
        "password" : "${password}",
        "roles" : [ "remove_monitoring_agent", "remote_monitoring_collector" ],
        "full_name" : "monitoring",
        "email" : "monitoring@example.com",
        "metadata" : {
          "intelligence" : 9
        }
      }
{{ end }}