{{ if   .Values.threehour }}
apiVersion: elastic.elastic-operator/v1
kind: ApiKey
metadata:
  name: {{.Release.Name}}-apikey-threehour
  namespace: {{ .Release.Namespace}}
spec:
  name: threehour
  cluster: {{ .Release.Name}}
  body: |
        {
          "name": "threehour",
          "expiration": "3h",   
          "role_descriptors": { 
            "role-a": {
              "cluster": [],
              "index": [
                {
                  "names": ["threehour-*"],
                  "privileges": ["write","create"]
                }
              ]
            }
          }
        }
{{ end}}        