{{ if   .Values.script1 }}
apiVersion: elastic.elastic-operator/v1
kind: Script
metadata:
  name: {{ .Release.Name}}-script-script1
  namespace: {{ .Release.Namespace}}
spec:
  name: script1
  cluster: {{ .Release.Name}}
  body: |
          {
            "script": {
              "lang": "painless",
              "source": """
              if (ctx._source.tags.contains(params['tag'])) 
              { 
                ctx.op = 'delete' 
              } else 
              { 
                ctx.op = 'none' 
              }
              """
                """
                   int count = 1;
                   return count;
                """

            }
          }  
{{ end }}