apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-logs
  namespace: observability
spec:
  releaseName: k8s-logs
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/charts/elastic-logs
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 5m0s
  values:

    filebeat:
      config: 
        version: 8.3.1

        collect: containerlogs
        image:
          registry: docker.elastic.co
          repository: beats/filebeat
          imagepullpolicy: IfNotPresent    

        securitycontext:
          runasuser: 1000
          fsgroup: 1000
          runasnonroot: true
        tolerations:
          key: tier
          value: application
        nodeselector:
          key: "tier"
          value:  "application"
        output:
          cluster: none
          apikey: apikey-elasticlogs
          httpca: es-http-ca-internal
          svc: 
            - es-http
          port: 9200      