{{ if .Values.elastic.config.monitoring.enabled }}
# filebeat resources
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name}}-filebeat
spec:
  type: filebeat
  version: {{ .Values.elastic.config.version }}
  config:

    output.elasticsearch:
      hosts: ["https://{{ .Values.elastic.config.monitoring.cluster}}-es-http:9200"]
      api_key: ${API_KEY}
      ssl.verification_mode: "certificate"
      ssl.certificate_authorities: ["/usr/share/metricbeat/certs/esmon-ca/tls.crt"]

    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  equals:
                    kubernetes.container.name: elastic
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log    
              - condition:
                  equals:
                    kubernetes.container.name: kibana
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log    
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    logging.json: true
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: {{ .Release.Name}}-filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata


        tolerations:
          - key: es-other
            operator: "Exists"
            effect: NoSchedule
          - key: es-data
            operator: "Exists"
            effect: NoSchedule
          - key: myapp
            operator: "Equal"
            value: "worker"
            effect: NoSchedule

        securityContext: 
          runAsUser: 1000
          fsGroup: 1000
          runAsNonRoot: true          
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        containers:
        - name: filebeat
          resources:
            limits:
              cpu: 300m
              memory: 750Mi
            requests:
              cpu: 200m
              memory: 750Mi          
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: filebeat-data
            mountPath: /usr/share/filebeat/data
          - mountPath: /usr/share/metricbeat/certs/esmon-ca
            name: esmon-ca
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: {{ .Values.elastic.config.monitoring.cluster}}-apikey-elasticlogs

        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - hostPath:
            path: /var/lib/{{ .Release.Name}}-data
            type: DirectoryOrCreate
          name: filebeat-dataxx
        - name: filebeat-data
          emptyDir: {}
          
        - name: esmon-ca
          secret:
            secretName: {{ .Values.elastic.config.monitoring.cluster}}-es-http-ca-internal
{{ end}}