# filebeat resources
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name}}-filebeat
spec:
  type: filebeat
  version: {{ .Values.filebeat.config.version }}
  image:  {{ .Values.filebeat.config.image.registry}}/{{ .Values.filebeat.config.image.repository}}:{{ .Values.filebeat.config.version }}
  config:

{{- include "filebeat.output" . | indent 4}}


    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
{{- include "filebeat.templates" . | indent 12}}


    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    logging.json: true
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: {{ .Release.Name}}-filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet


        tolerations:
{{- include "filebeat.tolerations" . | indent 10}}

        securityContext: 
          runAsUser: 1000
          fsGroup: 1000
          runAsNonRoot: true          
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        containers:
        - name: filebeat
          resources:
            limits:
              cpu: 300m
              memory: 750Mi
            requests:
              cpu: 200m
              memory: 750Mi          
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: filebeat-data
            mountPath: /usr/share/filebeat/data

{{- include "filebeat.volumemounts" . | indent 10}}


          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

{{- include "filebeat.apikey" . | indent 12}}

        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - hostPath:
            path: /var/lib/{{ .Release.Name}}-data
            type: DirectoryOrCreate
          name: filebeat-dataxx
        - name: filebeat-data
          emptyDir: {}
          
{{- include "filebeat.volumes" . | indent 8}}
