apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.myspacename }}
  labels:
    environment: {{ .Values.environment }}
    region: {{ .Values.region}}
    version: {{ .Values.filebeat.config.version}}