apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-logs
  namespace: observability
spec:
  releaseName: k8s-logs
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/charts/patchhelm
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 5m0s
