---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: patchhelm2
  namespace: observability
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./charts/patchhelm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-elastic
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: patchhelm2
      namespace: observability
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: patchhelm2
          namespace: observability
        spec:
          releaseName: patchhelm2
          values:
            filebeat:
              config:
                version: 8.4.1
      target:
        kind: HelmRelease
        name: patchhelm2
        namespace: observability