{{ if   .Values.role8 }}
apiVersion: elastic.elastic-operator/v1
kind: ElasticRole
metadata:
  name: {{ .Release.Name}}-role-role8
  namespace: {{ .Release.Namespace}}
spec:
  name: {{ .Release.Name}}-role-role8
  cluster: {{ .Release.Name}}
  body: |
    {
      "cluster": ["all"],
      "indices": [
          {
            "names": [ "role8-*" ],
            "privileges": ["all"]
          }
      ]
    }  
{{ end}}