apiVersion: elastic.elastic-operator/v1
kind: SyncSecret
metadata:
  name: {{.Release.Name}}
  namespace: {{ .Release.Namespace}}
spec:
  keyvaultsecret: eck-license
  k8snamespace: system
  k8ssecret: eck-license
  k8stype: opaque
  k8skey: license
  k8slabel: "license.k8s.elastic.co/scope: operator"
