---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: patchhelm
  namespace: observability
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./charts/patchhelm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-elastic
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env1
