{{ if  .Values.myrepo }}
apiVersion: elastic.elastic-operator/v1
kind: Repo
metadata:
  name: {{ .Release.Name}}-repo-myrepo
  namespace: {{ .Release.Namespace}}
spec:
  name: myrepo
  cluster: {{ .Release.Name}}
  body: |
          {
            "type": "azure",
            "settings": {
            }
          }  
{{ end}}            