---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name}}-elasticcluster-networkpolicy
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
  policyTypes:
    - Ingress
    - Egress
  egress:
  - ports:
    - port: 9300
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
  - ports:
    - port: 53
      protocol: UDP             
  ingress:
  - from:
    - podSelector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
    ports:
    - port: 9300
      protocol: TCP         