apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}  
{{- template "elastic.annotations" .}}  
{{- template "elastic.spec" .}}