---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name}}-elastic-networkpolicy
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
  policyTypes:
    - Ingress
    - Egress

  egress:
  - ports:
    - port: 9300
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
  - ports:
    - port: 53
      protocol: UDP     
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.elasticcontroller.namespace }}
        - podSelector:
            matchLabels:
              app: {{ .Values.elasticcontroller.name}}
      ports:
      - protocol: TCP
        port: 9200
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.eck.namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.eck.name}}
      ports:
      - protocol: TCP
        port: 9200
    - from:
      - podSelector:
          matchLabels:
            elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
      ports:
      - port: 9300
        protocol: TCP  