{{ if .Values.fleet.config.enabled }}
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace}}
spec:
  version: {{ .Values.elastic.config.version }}
  kibanaRef:
    name: {{ .Release.Name }}
  elasticsearchRefs:
  - name: {{ .Release.Name }}
  mode: {{ .Values.fleet.config.mode }}
  fleetServerEnabled: true
  deployment:
    replicas: {{ .Values.fleet.config.count }}
    podTemplate:
      spec:
        serviceAccountName: {{ .Release.Name}}-elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
{{ end }}