{{ if .Values.fleet.config.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name}}-elastic-agent
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-elastic-agent
  namespace: {{ .Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name}}-elastic-agent
  apiGroup: rbac.authorization.k8s.io
{{ end }}  