apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 50m    
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "{{.Release.Name}}-affinity"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"  
  name: {{ .Release.Name}}-kb-ingress
  namespace: {{ .Release.Namespace}}

spec:
  rules:
  - host: {{ .Release.Name}}-kb
    http:
      paths: 
      - path: /
        backend:
          service:
            name: {{ .Release.Name}}-kb-http
            port:
              number: 5601
        pathType: ImplementationSpecific

