---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name}}-kibana-networkpolicy
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      kibana.k8s.elastic.co/name: {{ .Release.Name}}
  policyTypes:
    - Ingress
    - Egress
  egress:
  - ports:
    - port: 9200
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}}     
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.elasticcontroller.namespace }}
        - podSelector:
            matchLabels:
              app: {{ .Values.elasticcontroller.name}}
      ports:
      - protocol: TCP
        port: 5601
    - from:
      - podSelector:
          matchLabels:
            beat.k8s.elastic.co/name: {{ .Release.Name}}-metricbeat
      ports:
      - port: 5601
        protocol: TCP          
