---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name}}-kibana-networkpolicy
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      kibana.k8s.elastic.co/name: {{ .Release.Name}}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.elasticcontroller.namespace }}
        - podSelector:
            matchLabels:
              app: {{ .Values.elasticcontroller.name}}
      ports:
      - protocol: TCP
        port: 5601
