---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name}}-metricbeat-networkpolicy
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels:
      beat.k8s.elastic.co/name: {{ .Release.Name}}-metricbeat
  policyTypes:
    - Egress
  egress:
  - ports:
    - port: 9200
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name:  {{ .Release.Name}} 
  - ports:
    - port: 5601
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          kibana.k8s.elastic.co/name: {{ .Release.Name}}        
  - ports:
    - port: 53
      protocol: UDP
  - ports:
    - port: 443
      protocol: TCP
    to:
      - ipBlock:
          cidr: 172.18.0.1/32
      - ipBlock:
          cidr: 10.144.112.4/32