{{ if .Values.elastic.config.monitoring.enabled }}
---
# metricbeat resources
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name}}-metricbeat
  namespace: {{ .Release.Namespace }}
spec:
  type: metricbeat
  version: {{ .Values.elastic.config.version }}
  config:

    output.elasticsearch:
      hosts: ["https://{{ .Values.elastic.config.monitoring.cluster}}-es-http:9200"]
      api_key: ${API_KEY}
      ssl.verification_mode: "certificate"
      ssl.certificate_authorities: ["/usr/share/metricbeat/certs/esmon-ca/tls.crt"]

    metricbeat:
      autodiscover:
        providers:
          - type: kubernetes
            scope: cluster
            namespace: {{ .Release.Namespace}}
            hints.enabled: false
            templates:
              - condition:
                  contains:
                    kubernetes.labels.elasticsearch_k8s_elastic_co/cluster-name: {{ .Release.Name }}
                config:
                  - module: elasticsearch
                    metricsets:
                      - ccr
                      - cluster_stats
                      - enrich
                      - index
                      - index_recovery
                      - index_summary
                      - ml_job
                      - node_stats
                      - shard
                    period: {{ .Values.elastic.config.monitoring.period }}
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.verification_mode: "certificate"
                    ssl.certificate_authorities: ["/usr/share/metricbeat/certs/es-ca/tls.crt"]
                    xpack.enabled: true
              - condition:
                  contains:
                    kubernetes.labels.kibana_k8s_elastic_co/name: {{ .Release.Name }}
                config:
                  - module: kibana
                    metricsets:
                      - stats
                    period: {{ .Values.elastic.config.monitoring.period }}
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.certificate_authorities: ["/usr/share/metricbeat/certs/kb-ca/tls.crt"]
                    ssl.verification_mode: "certificate"
                    xpack.enabled: true    
  deployment:
    podTemplate:
      spec:
        serviceAccountName: {{ .Release.Name}}-metricbeat
        automountServiceAccountToken: true
        # required to read /etc/beat.yml

        securityContext: 
          runAsUser: 1000
          fsGroup: 1000
          runAsNonRoot: true

        containers:
        - name: metricbeat
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 1
          env:
          - name: MONITORED_ES_USERNAME
            value: elastic
          - name: MONITORED_ES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: elastic
                name: {{ .Release.Name}}-es-elastic-user
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                key: apikey
                name: {{ .Values.elastic.config.monitoring.cluster}}-apikey-monitoring

          volumeMounts:
          - mountPath: /usr/share/metricbeat/data
            name: data-volume                
          - mountPath: /usr/share/metricbeat/certs/es-ca
            name: es-ca
          - mountPath: /usr/share/metricbeat/certs/kb-ca
            name: kb-ca
          - mountPath: /usr/share/metricbeat/certs/esmon-ca
            name: esmon-ca

        volumes:
        - name: data-volume
          emptyDir: {}

        - name: es-ca
          secret:
            secretName: {{ .Release.Name}}-es-http-ca-internal

        - name: esmon-ca
          secret:
            secretName: {{ .Values.elastic.config.monitoring.cluster}}-es-http-ca-internal

        - name: kb-ca
          secret:
            secretName: {{ .Release.Name}}-kb-http-ca-internal
---
{{ end }}