{{ if  .Values.rally }}
apiVersion: elastic.elastic-operator/v1
kind: KibanaSpace
metadata:
  name: {{ .Release.Name}}-kibanaspace-rally
  namespace: {{ .Release.Namespace}}
spec:
  name: rally
  cluster: {{ .Release.Name}}
  body: |
    {
        "id": "rally",
        "name": "rally",
        "description": "my fancy rally space",
        "initials": "m1"
    }
{{ end }}    