apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: cluster8
  namespace: observability
spec:
  releaseName: cluster8
  targetNamespace: observability
  chart:
    spec:
      chart: /charts/elastic-cluster
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:
    myvar: yeah

    master:
      nodeset: 
        count: 1    

    data:
      nodeset: 
        count: 0

    datahot:
      nodeset: 
        count: 1
        
    ingest:
      nodeset: 
        count: 1
