apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-logs
  namespace: observability
spec:
  releaseName: elastic-logs
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/charts/elastic-logs
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 5m0s
  values:
    topology:
      enabled: false

