

production:
  enabled: false


elasticcontroller:
  namespace: system
  name: iitech-elasticoperator

eck:
  namespace: system
  name: elastic-operator

kibana:
  config:
    count: 1
    endpoint: "https://kibana_endpoint"
    securitycontext:
      runasuser: 1000
      fsgroup: 1000
      runasnonroot: true
    tolerations:
      key: tier
      value: application
    nodeselector:
      key: "tier"
      value:  "application"   
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 2Gi
      cpu: 2

elastic:
  config: 
    version: 8.1.0
    zoneawareness: true
    affinity: false
    oidc:
      enabled: true
      name: myazure
      description: "login with oidc"
      claimurl: "http://example.com/claims/groups"
      clientid: "clientid"
      tenantid: "tenantid"
    securitycontext:
      runasuser: 1000
      fsgroup: 1000
      runasnonroot: true
    tolerations:
      key: tier
      value: application
    nodeselector:
      key: "tier"
      value:  "application"
    monitoring:
      enabled: false
      cluster: none
      period: 30s

master:
  nodeset:
    name: master 
    count: 3
    roles: 
      - '"master"'
      - '"remote_cluster_client"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

data:
  nodeset: 
    name: data
    count: 2    
    roles: 
      - '"data"'
      - '"ml"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datahot:
  nodeset: 
    name: datahot
    count: 0   
    roles: 
      - '"data_hot"'
      - '"data_content"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datawarm:
  nodeset: 
    name: datawarm
    count: 0        
    roles: 
      - '"data_warm"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datacold:
  nodeset: 
    name: datacold
    count: 0        
    roles: 
      - '"data_cold"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datafrozen:
  nodeset: 
    name: datafrozen
    count: 0        
    shared_cache: 100000b
    roles: 
      - '"data_frozen"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

ingest:
  nodeset: 
    name: ingest
    count: 0            
    roles: 
      - '"ingest"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

coord:
  nodeset: 
    name: coord
    count: 0            
    roles: 
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

ml:
  nodeset: 
    name: ml
    count: 0            
    roles: 
      - '"remote_cluster_client"'
      - '"ml"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

transform:
  nodeset: 
    name: transform
    count: 0            
    roles: 
      - '"remote_cluster_client"'
      - '"transform"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

