myvar: prod

oidc:
  enabled: true
  claimurl: "http://example.com/claims/groups"


production:
  enabled: false


elastic:
  version: 8.1.0

master:
  nodeset:
    name: master 
    count: 3
    shared_cache: 0     
    roles: 
      - '"master"'
      - '"remote_cluster_client"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

data:
  nodeset: 
    name: data
    count: 2    
    shared_cache: 0     
    roles: 
      - '"data"'
      - '"ml"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datahot:
  nodeset: 
    name: datahot
    count: 0   
    shared_cache: 0     
    roles: 
      - '"data_hot"'
      - '"data_content"'    
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datawarm:
  nodeset: 
    name: datawarm
    count: 0        
    shared_cache: 0     
    roles: 
      - '"data_warm"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datacold:
  nodeset: 
    name: datacold
    count: 0        
    shared_cache: 0     
    roles: 
      - '"data_cold"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

datafrozen:
  nodeset: 
    name: datafrozen
    count: 0        
    shared_cache: 100000b
    roles: 
      - '"data_frozen"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

ingest:
  nodeset: 
    name: ingest
    count: 0            
    shared_cache: 0     
    roles: 
      - '"ingest"'
      - '"remote_cluster_client"'
    storage: 1Gi
    storageclass: "standard"
    limits: 
      memory: 2Gi
      cpu: 2
    requests: 
      memory: 1Gi
      cpu: 1

