apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: elasticoperator
  namespace: "system"
spec:
  releaseName: elasticoperator
  targetNamespace: "system"
  chart:
    spec:
      chart: ./charts/elasticoperator
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m

