apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: iitech-elasticoperator
  namespace: system
spec:
  releaseName: iitech-elasticoperator
  targetNamespace: system
  chart:
    spec:
      chart: ./charts/elasticoperator
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m

