apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: elasticoperator
  namespace: observability
spec:
  releaseName: elasticoperator
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/elasticoperator
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:
    configmap: 
      healthPort: 25002

