{{ if  .Values.myindextemplate }}
apiVersion: elastic.elastic-operator/v1
kind: LegacyIndexTemplate
metadata:
  name: {{ .Release.Name}}-legacyindextemplate-myindextemplate
  namespace: {{ .Release.Namespace}}
spec:
  name: myindextemplate
  cluster: {{ .Release.Name}}
  body: |
            {
              "index_patterns": ["te*", "bar*"],
              "settings": {
                "number_of_shards": 1
              },
              "mappings": {
                "_source": {
                  "enabled": false
                },
                "properties": {
                  "host_name": {
                    "type": "keyword"
                  },
                  "created_at": {
                    "type": "date",
                    "format": "EEE MMM dd HH:mm:ss Z yyyy"
                  }
                }
              }
            }
{{ end}}            