apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: cluster6
  namespace: observability
spec:
  releaseName: cluster6
  targetNamespace: observability
  chart:
    spec:
      chart: /charts/elastic-cluster
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:
    myvar: yeah

    data:
      nodeset: 
        count: 0    

    datahot:
      nodeset: 
        count: 2
        
