apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: k8s-logs
  namespace: observability
spec:
  releaseName: k8s-logs
  targetNamespace: observability
  chart:
    spec:
      chart: ./charts/elastic-logs
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-elastic
        namespace: flux-system
  interval: 1m
  values:

    filebeat:
      config:
        collect: containerlogs
        version: 8.3.1
        output:
          cluster: cluster14
