---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name}}-operator-{{ .Values.Operator.Role }}
rules:
  - apiGroups:
        - {{ .Values.ConfigMap.ApiGroup}}
    resources:
      - indextemplates
      - kibanaspaces
      - ilms
      - slms
      - elasticroles
      - rolemappings
      - clustersettings
      - ingestpipelines
      - repos
      - apikeys
      - componenttemplates
      - legacyindextemplates
      - watchers
      - scripts
      - transforms
      - dataviews
      - connectors
      - alertrules
      - syncsecrets
      - elasticusers
      - elasticsecrets
      - serviceaccounttokens
    verbs: ["get","watch","list" ]
  - apiGroups:
        - ""
    resources:
      - secrets
      - pods
    verbs: ["get", "list", "delete"]    
  - apiGroups:
        - ""
    resources:
      - persistentvolumeclaims
      - configmaps
      - namespaces
    verbs: ["get",  "list" ]        