---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name}}-operator-{{ .Values.Operator.Role }}
rules:
  - apiGroups:
        - ""
        #- apps
        #- autoscaling
        #- batch
        #- extensions
        #- policy
        #- rbac.authorization.k8s.io
        - {{ .Values.ConfigMap.ApiGroup}}
    resources:
      #- pods
      #- componentstatuses
      #- configmaps
      #- daemonsets
      #- deployments
      #- events
      #- endpoints
      #- horizontalpodautoscalers
      #- ingress
      #- jobs
      #- limitranges
      #- namespaces
      #- nodes
      #- pods
      #- persistentvolumes
      #- persistentvolumeclaims
      #- resourcequotas
      #- replicasets
      #- replicationcontrollers
      #- serviceaccounts
      #- services
      - configmaps
      - namespaces
      - indextemplates
      - kibanaspaces
      - ilms
      - slms
      - elasticroles
      - rolemappings
      - clustersettings
      - ingestpipelines
      - repos
      - apikeys
      - componenttemplates
      - legacyindextemplates
      - watchers
      - scripts
      - transforms
      - dataviews
      - connectors
      - alertrules
      - syncsecrets
      - elasticusers
      - elasticsecrets
      - serviceaccounttokens
    verbs: ["get","watch","list" ]
  - apiGroups:
        - ""
    resources:
      - secrets
      - pods
    verbs: ["get", "list", "delete"]    
  - apiGroups:
        - ""
    resources:
      - pvcs
    verbs: ["get",  "list" ]        