---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-configmap
  namespace : {{ .Release.Namespace}}
data:
  # property-like keys; each key maps to a simple value
  apikeyRollover: "{{ .Values.ConfigMap.apikeyRollover}}"
  maxRetries: "{{ .Values.ConfigMap.maxRetries}}"
  keyVault: "{{ .Values.ConfigMap.keyVault}}"
  elasticUserSecretSuffix: "{{ .Values.ConfigMap.elasticUserSecretSuffix}}"
  ReconLoopInterval: "{{ .Values.ConfigMap.ReconLoopInterval}}"
  ApiGroup: "{{ .Values.ConfigMap.ApiGroup}}"
  ApiVersion: "{{ .Values.ConfigMap.ApiVersion}}"
  CacheTtl: "{{ .Values.ConfigMap.CacheTtl}}"
  Namespace: "{{ .Values.ConfigMap.Namespace}}"
  LongRunningCheck: "{{ .Values.ConfigMap.LongRunningCheck}}"
  LongRunningMax: "{{ .Values.ConfigMap.LongRunningMax}}"
  SyncSecrets: "{{ .Values.ConfigMap.SyncSecrets}}"
