---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  namespace : {{ .Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}
        version: v1
    spec:
      serviceAccountName: {{ .Release.Name}}-{{ .Values.Operator.Sa }}
      containers:
      - name: {{ .Release.Name}}
#        imagePullPolicy: IfNotPresent
        image: elasticcontroller:v3.0.4
        resources:
          limits:
            memory: {{ .Values.limits.memory}}
            cpu: {{ .Values.limits.cpu}}
          requests:
            memory: {{ .Values.requests.memory}}
            cpu: {{ .Values.requests.cpu}}          
        ports:
        - containerPort: {{ .Values.ConfigMap.healthPort}}
          name: healthport
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /api/readiness
            port: {{ .Values.ConfigMap.healthPort}}
          initialDelaySeconds: 60
          periodSeconds: 30          

        livenessProbe:
          httpGet:
            path: /api/liveness
            port: {{ .Values.ConfigMap.healthPort}}
          initialDelaySeconds: 30
          periodSeconds: 30

        startupProbe:
          httpGet:
            path: /api/liveness
            port: {{ .Values.ConfigMap.healthPort}}
          failureThreshold: 30
          periodSeconds: 10                   

        env:
        # Define the environment variable
        - name: NAMESPACE
          value: "{{ .Release.Namespace}}"
        - name: CONFIGMAP
          value: "{{ .Release.Name}}-configmap"
        - name: HEALTHPORT
          value: "{{ .Values.ConfigMap.healthPort}}"

