---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  namespace : {{ .Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}
        version: v1
    spec:
      serviceAccountName: {{ .Release.Name}}-svc
      containers:
      - name: {{ .Release.Name}}
        imagePullPolicy: IfNotPresent
        image: deckkh/elasticcontroller:v1.2.43
        ports:
        - containerPort: {{ .Values.configmap.healthPort}}
          name: healthPort
          protocol: TCP
        env:
        # Define the environment variable
        - name: NAMESPACE
          value: "{{ .Release.Namespace}}"
        - name: CONFIGMAP
          value: "{{ .Release.Name}}-configmap"
        - name: HEALTHPORT
          value: "{{ .Values.configmap.healthPort}}"

      imagePullSecrets:
      - name: regcred
