---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-rolebinding-tenant
  namespace: {{ .Values.Operator.TenantNamespace}}
subjects:
- namespace: {{ .Release.Namespace}} 
  kind: ServiceAccount
  name: {{ .Release.Name}}-{{ .Values.Operator.Sa}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name}}-{{ .Values.Operator.Role }}
