---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-cluster-role-binding
  namespace: {{ .Operator.Namespace}}
subjects:
- namespace: {{ .Operator.Namespace}} 
  kind: ServiceAccount
  name: {{ .Release.Name}}-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-role
