{{ if   .Values.routingallocationdisk }}
apiVersion: elastic.elastic-operator/v1
kind: ClusterSetting
metadata:
  name: {{ .Release.Name}}-clustersettings-routingallocationdisk
  namespace: {{ .Release.Namespace}}
spec:
  name: routingallocationdisk
  cluster: {{ .Release.Name}}
  body: |
            {
              "persistent" : {
                "cluster.routing.allocation.disk.threshold_enabled": true,
                "cluster.routing.allocation.disk.watermark.low": "80%",
                "cluster.routing.allocation.disk.watermark.high": "85%"
              }
            }  
  bodyRemove: |
            {
              "persistent" : {
                "cluster.routing.allocation.disk.threshold_enabled": null,
                "cluster.routing.allocation.disk.watermark.low": null,
                "cluster.routing.allocation.disk.watermark.high": null
              }
            }  
{{ end}}